### ISSUE TITLE
[Documentation Update]: Define Bicep UDT specs and usage

### ISSUE THREAD

**Issue by eriqua** [Azure/Azure-Verified-Modules#1559]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Description

Document both specs and contribution guidelines related to User Defined Types (UDT) for Bicep resource modules

```[tasklist]
### Tasks
- [ ] New Spec - All Bicep resource modules MUST leverage the common type utility module for shared interfaces (document exceptions)
- [ ] Contribution guidelines - how to use AVMCommonTypes utility module in resource modules
- [ ] New Spec - All objects and array of objects SHOULD define UDT to better leverage automatic documentation and intellisense.
- [ ] New Spec - All UDT MUST be singular and non nullable
- [ ] Contribution guidelines - how to define UDT for objects and array of objects
```

**Comment by AlexanderSehr** [comment]
Ref: https://github.com/Azure/bicep-registry-modules/pull/3582#issuecomment-2417782383
